//! `CGEventField` values used by `CGEventGet/Set*ValueField`.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CGEventField {
    MouseEventNumber,
    MouseEventClickState,
    MouseEventPressure,
    MouseEventButtonNumber,
    MouseEventDeltaX,
    MouseEventDeltaY,
    MouseEventInstantMouser,
    MouseEventSubtype,
    KeyboardEventAutorepeat,
    KeyboardEventKeycode,
    KeyboardEventKeyboardType,
    ScrollWheelEventDeltaAxis1,
    ScrollWheelEventDeltaAxis2,
    ScrollWheelEventDeltaAxis3,
    ScrollWheelEventFixedPtDeltaAxis1,
    ScrollWheelEventFixedPtDeltaAxis2,
    ScrollWheelEventFixedPtDeltaAxis3,
    ScrollWheelEventPointDeltaAxis1,
    ScrollWheelEventPointDeltaAxis2,
    ScrollWheelEventPointDeltaAxis3,
    ScrollWheelEventScrollPhase,
    ScrollWheelEventScrollCount,
    ScrollWheelEventMomentumPhase,
    ScrollWheelEventInstantMouser,
    TabletEventPointX,
    TabletEventPointY,
    TabletEventPointZ,
    TabletEventPointButtons,
    TabletEventPointPressure,
    TabletEventTiltX,
    TabletEventTiltY,
    TabletEventRotation,
    TabletEventTangentialPressure,
    TabletEventDeviceID,
    TabletEventVendor1,
    TabletEventVendor2,
    TabletEventVendor3,
    TabletProximityEventVendorID,
    TabletProximityEventTabletID,
    TabletProximityEventPointerID,
    TabletProximityEventDeviceID,
    TabletProximityEventSystemTabletID,
    TabletProximityEventVendorPointerType,
    TabletProximityEventVendorPointerSerialNumber,
    TabletProximityEventVendorUniqueID,
    TabletProximityEventCapabilityMask,
    TabletProximityEventPointerType,
    TabletProximityEventEnterProximity,
    EventTargetProcessSerialNumber,
    EventTargetUnixProcessID,
    EventSourceUnixProcessID,
    EventSourceUserData,
    EventSourceUserID,
    EventSourceGroupID,
    EventSourceStateID,
    ScrollWheelEventIsContinuous,
    MouseEventWindowUnderMousePointer,
    MouseEventWindowUnderMousePointerThatCanHandleThisEvent,
    EventUnacceleratedPointerMovementX,
    EventUnacceleratedPointerMovementY,
    ScrollWheelEventMomentumOptionPhase,
    ScrollWheelEventAcceleratedDeltaAxis1,
    ScrollWheelEventAcceleratedDeltaAxis2,
    ScrollWheelEventRawDeltaAxis1,
    ScrollWheelEventRawDeltaAxis2,
}

impl CGEventField {
    #[must_use]
    pub const fn raw(self) -> u32 {
        match self {
            Self::MouseEventNumber => 0,
            Self::MouseEventClickState => 1,
            Self::MouseEventPressure => 2,
            Self::MouseEventButtonNumber => 3,
            Self::MouseEventDeltaX => 4,
            Self::MouseEventDeltaY => 5,
            Self::MouseEventInstantMouser => 6,
            Self::MouseEventSubtype => 7,
            Self::KeyboardEventAutorepeat => 8,
            Self::KeyboardEventKeycode => 9,
            Self::KeyboardEventKeyboardType => 10,
            Self::ScrollWheelEventDeltaAxis1 => 11,
            Self::ScrollWheelEventDeltaAxis2 => 12,
            Self::ScrollWheelEventDeltaAxis3 => 13,
            Self::ScrollWheelEventFixedPtDeltaAxis1 => 93,
            Self::ScrollWheelEventFixedPtDeltaAxis2 => 94,
            Self::ScrollWheelEventFixedPtDeltaAxis3 => 95,
            Self::ScrollWheelEventPointDeltaAxis1 => 96,
            Self::ScrollWheelEventPointDeltaAxis2 => 97,
            Self::ScrollWheelEventPointDeltaAxis3 => 98,
            Self::ScrollWheelEventScrollPhase => 99,
            Self::ScrollWheelEventScrollCount => 100,
            Self::ScrollWheelEventMomentumPhase => 123,
            Self::ScrollWheelEventInstantMouser => 14,
            Self::TabletEventPointX => 15,
            Self::TabletEventPointY => 16,
            Self::TabletEventPointZ => 17,
            Self::TabletEventPointButtons => 18,
            Self::TabletEventPointPressure => 19,
            Self::TabletEventTiltX => 20,
            Self::TabletEventTiltY => 21,
            Self::TabletEventRotation => 22,
            Self::TabletEventTangentialPressure => 23,
            Self::TabletEventDeviceID => 24,
            Self::TabletEventVendor1 => 25,
            Self::TabletEventVendor2 => 26,
            Self::TabletEventVendor3 => 27,
            Self::TabletProximityEventVendorID => 28,
            Self::TabletProximityEventTabletID => 29,
            Self::TabletProximityEventPointerID => 30,
            Self::TabletProximityEventDeviceID => 31,
            Self::TabletProximityEventSystemTabletID => 32,
            Self::TabletProximityEventVendorPointerType => 33,
            Self::TabletProximityEventVendorPointerSerialNumber => 34,
            Self::TabletProximityEventVendorUniqueID => 35,
            Self::TabletProximityEventCapabilityMask => 36,
            Self::TabletProximityEventPointerType => 37,
            Self::TabletProximityEventEnterProximity => 38,
            Self::EventTargetProcessSerialNumber => 39,
            Self::EventTargetUnixProcessID => 40,
            Self::EventSourceUnixProcessID => 41,
            Self::EventSourceUserData => 42,
            Self::EventSourceUserID => 43,
            Self::EventSourceGroupID => 44,
            Self::EventSourceStateID => 45,
            Self::ScrollWheelEventIsContinuous => 88,
            Self::MouseEventWindowUnderMousePointer => 91,
            Self::MouseEventWindowUnderMousePointerThatCanHandleThisEvent => 92,
            Self::EventUnacceleratedPointerMovementX => 170,
            Self::EventUnacceleratedPointerMovementY => 171,
            Self::ScrollWheelEventMomentumOptionPhase => 173,
            Self::ScrollWheelEventAcceleratedDeltaAxis1 => 176,
            Self::ScrollWheelEventAcceleratedDeltaAxis2 => 175,
            Self::ScrollWheelEventRawDeltaAxis1 => 178,
            Self::ScrollWheelEventRawDeltaAxis2 => 177,
        }
    }

    #[must_use]
    pub const fn from_raw(raw: u32) -> Option<Self> {
        match raw {
            0 => Some(Self::MouseEventNumber),
            1 => Some(Self::MouseEventClickState),
            2 => Some(Self::MouseEventPressure),
            3 => Some(Self::MouseEventButtonNumber),
            4 => Some(Self::MouseEventDeltaX),
            5 => Some(Self::MouseEventDeltaY),
            6 => Some(Self::MouseEventInstantMouser),
            7 => Some(Self::MouseEventSubtype),
            8 => Some(Self::KeyboardEventAutorepeat),
            9 => Some(Self::KeyboardEventKeycode),
            10 => Some(Self::KeyboardEventKeyboardType),
            11 => Some(Self::ScrollWheelEventDeltaAxis1),
            12 => Some(Self::ScrollWheelEventDeltaAxis2),
            13 => Some(Self::ScrollWheelEventDeltaAxis3),
            14 => Some(Self::ScrollWheelEventInstantMouser),
            15 => Some(Self::TabletEventPointX),
            16 => Some(Self::TabletEventPointY),
            17 => Some(Self::TabletEventPointZ),
            18 => Some(Self::TabletEventPointButtons),
            19 => Some(Self::TabletEventPointPressure),
            20 => Some(Self::TabletEventTiltX),
            21 => Some(Self::TabletEventTiltY),
            22 => Some(Self::TabletEventRotation),
            23 => Some(Self::TabletEventTangentialPressure),
            24 => Some(Self::TabletEventDeviceID),
            25 => Some(Self::TabletEventVendor1),
            26 => Some(Self::TabletEventVendor2),
            27 => Some(Self::TabletEventVendor3),
            28 => Some(Self::TabletProximityEventVendorID),
            29 => Some(Self::TabletProximityEventTabletID),
            30 => Some(Self::TabletProximityEventPointerID),
            31 => Some(Self::TabletProximityEventDeviceID),
            32 => Some(Self::TabletProximityEventSystemTabletID),
            33 => Some(Self::TabletProximityEventVendorPointerType),
            34 => Some(Self::TabletProximityEventVendorPointerSerialNumber),
            35 => Some(Self::TabletProximityEventVendorUniqueID),
            36 => Some(Self::TabletProximityEventCapabilityMask),
            37 => Some(Self::TabletProximityEventPointerType),
            38 => Some(Self::TabletProximityEventEnterProximity),
            39 => Some(Self::EventTargetProcessSerialNumber),
            40 => Some(Self::EventTargetUnixProcessID),
            41 => Some(Self::EventSourceUnixProcessID),
            42 => Some(Self::EventSourceUserData),
            43 => Some(Self::EventSourceUserID),
            44 => Some(Self::EventSourceGroupID),
            45 => Some(Self::EventSourceStateID),
            88 => Some(Self::ScrollWheelEventIsContinuous),
            91 => Some(Self::MouseEventWindowUnderMousePointer),
            92 => Some(Self::MouseEventWindowUnderMousePointerThatCanHandleThisEvent),
            93 => Some(Self::ScrollWheelEventFixedPtDeltaAxis1),
            94 => Some(Self::ScrollWheelEventFixedPtDeltaAxis2),
            95 => Some(Self::ScrollWheelEventFixedPtDeltaAxis3),
            96 => Some(Self::ScrollWheelEventPointDeltaAxis1),
            97 => Some(Self::ScrollWheelEventPointDeltaAxis2),
            98 => Some(Self::ScrollWheelEventPointDeltaAxis3),
            99 => Some(Self::ScrollWheelEventScrollPhase),
            100 => Some(Self::ScrollWheelEventScrollCount),
            123 => Some(Self::ScrollWheelEventMomentumPhase),
            170 => Some(Self::EventUnacceleratedPointerMovementX),
            171 => Some(Self::EventUnacceleratedPointerMovementY),
            173 => Some(Self::ScrollWheelEventMomentumOptionPhase),
            175 => Some(Self::ScrollWheelEventAcceleratedDeltaAxis2),
            176 => Some(Self::ScrollWheelEventAcceleratedDeltaAxis1),
            177 => Some(Self::ScrollWheelEventRawDeltaAxis2),
            178 => Some(Self::ScrollWheelEventRawDeltaAxis1),
            _ => None,
        }
    }

    #[must_use]
    pub const fn is_double_valued(self) -> bool {
        matches!(
            self,
            Self::MouseEventPressure
                | Self::ScrollWheelEventFixedPtDeltaAxis1
                | Self::ScrollWheelEventFixedPtDeltaAxis2
                | Self::ScrollWheelEventFixedPtDeltaAxis3
                | Self::TabletEventPointPressure
                | Self::TabletEventTiltX
                | Self::TabletEventTiltY
                | Self::TabletEventRotation
                | Self::TabletEventTangentialPressure
        )
    }
}
